# Generated by Django 3.2.6 on 2021-09-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='e_image1',
            field=models.ImageField(blank=True, null=True, upload_to='extra_image'),
        ),
        migrations.AddField(
            model_name='item',
            name='e_image2',
            field=models.ImageField(blank=True, null=True, upload_to='extra_image'),
        ),
        migrations.AddField(
            model_name='item',
            name='e_image3',
            field=models.ImageField(blank=True, null=True, upload_to='extra_image'),
        ),
    ]
